// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP5VBkZVnV5afCk_Ub7uD2plu73yHAclU',
    appId: '1:286642538221:web:7a98aff3d26d823772aee4',
    messagingSenderId: '286642538221',
    projectId: 'contacts-5fc5f',
    authDomain: 'contacts-5fc5f.firebaseapp.com',
    storageBucket: 'contacts-5fc5f.firebasestorage.app',
    measurementId: 'G-75GY800B55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD620As0Suhx8WM0Dw8zfcqx2R27B6NIeQ',
    appId: '1:286642538221:android:b1a65285240836f372aee4',
    messagingSenderId: '286642538221',
    projectId: 'contacts-5fc5f',
    storageBucket: 'contacts-5fc5f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP5VBkZVnV5afCk_Ub7uD2plu73yHAclU',
    appId: '1:286642538221:web:2f3ab4ba66d073cd72aee4',
    messagingSenderId: '286642538221',
    projectId: 'contacts-5fc5f',
    authDomain: 'contacts-5fc5f.firebaseapp.com',
    storageBucket: 'contacts-5fc5f.firebasestorage.app',
    measurementId: 'G-P1RGKZQWR5',
  );
}
